Feature/current course details
BloomTech-Labs/coder-heroes-be pull request #101
Opened 2022-04-29 17:09 UTC by dconley1212

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Loom Video

Please paste a link here of a quick loom video walking through what you did in your PR .

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have removed unnecessary comments/console logs from my code
- [ ] I have made corresponding changes to the documentation if necessary (optional)
- [ ] My changes generate no new warnings
- [ ] I have checked my code and corrected any misspellings
- [ ] No duplicate code left within changed files
- [ ] Size of pull request kept to a minimum
- [ ] Pull request description clearly describes changes made & motivations for said changes
https://www.loom.com/share/056f7508a4e94c8eb9e81ae88ce56908

2022-04-29 17:19 UTC, dconley1212 commented
https://www.loom.com/share/056f7508a4e94c8eb9e81ae88ce56908

2022-04-29 20:55 UTC, dconley1212 commented
https://www.loom.com/share/db53b21b775e439eb6d673fdd460ba56

2022-04-29 20:56 UTC, EduarddoEscobar approved these changes
Overall great work!

2022-04-29 20:56 UTC, EduarddoEscobar commented on api/children/childrenModel.js
> +    .join('instructors', 'instructors.instructor_id', 'courses.instructor_id')
Good job shortening enrolledCourses

2022-04-29 20:56 UTC, EduarddoEscobar commented on api/children/childrenRouter.js
> +  '/:child_id/enrollments',
Love the more specific endpoint!

2022-05-02 23:44 UTC, joeys1122 approved these changes
Overall great work getting these endpoints fixed!

2022-05-02 23:44 UTC, joeys1122 commented on api/children/childrenMiddleware.js
> +  const id = req.params.child_id;
Good idea changing the id names, it's good to specify where exactly the id comes from

2022-05-02 23:44 UTC, joeys1122 commented on api/children/childrenModel.js
> +const getEnrolledCourses = async (child_id) => {
thank you for updating this function, now the child enrollments endpoint gives back much more useful data!

2022-05-03 21:08 UTC, aamay022 reviewed
Great work inside the model function to retrieve more than just the children object, but the profile data as well. And great fix in changing the params, to know we are grabbing the child_id.

2022-05-03 22:31 UTC, Berenika14 requested changes
If you could add a short description in the PR and check all the boxes that represent the changes you made it will be easier to understand the changes without the need to watch the loom video. Overall great work on the code.

2022-05-06 01:04 UTC, Ike888 approved these changes
Great work fixing those linter errors.

2022-06-13 15:03 UTC, ivanovicu approved these changes

2022-06-23 21:14 UTC, spencerlonghurst approved these changes
Based on what I can see, everything looks good and solid. No comments or console.logs. Great job!

2022-06-23 21:55 UTC, leewp8 approved these changes
Looks like some useful updates to the codebase. You've both done a great job of writing the code so it looks well organized and easy for another dev to understand.

2022-06-23 22:33 UTC, Ogden-R approved these changes
These updates look great. i love that you put more details for the child signup endpoint.

2022-06-24 02:10 UTC, ShahWahidy approved these changes
you guys did a great job refactor the code and getting rid of redundancy. child looks much cleaner with just the spread operator instead of piling up unnecessary code. good luck with future PRs

2022-06-24 02:29 UTC, dirkknibbe approved these changes

2022-06-24 02:29 UTC, dirkknibbe commented on api/children/childrenRouter.js
> +  async function (req, res, next) {
I like the use of your checkChildExist middleware as well as the addition of authRequired 👍

2022-06-24 02:29 UTC, dirkknibbe commented on api/children/childrenRouter.js
> +  '/:child_id/enrollments',
Nice, child_id is so much clearer

2022-06-27 16:20 UTC, ashtilawat23 requested changes
To preserve the package-lock on Main, please copy and paste the package-lock from the main branch on the browser into your branch on VScode. You can "View Raw" and open the package-lock on the browser. Then use Cmd A to select all, Cmd C and Cmd V to copy paste.

2022-06-27 16:20 UTC, ashtilawat23 commented on package-lock.json
> +  "lockfileVersion": 1,
This PR can't be merged until the package-lock is the same as the one on Main

2022-06-27 20:10 UTC, jose-mercado approved these changes
Great job refactoring the childrenModel, I also REALLY appreciate including a loom to the update, I think it provides more context and Isn't done enough by others! Awesome work!

2022-07-13 16:55 UTC, ivanovicuros approved these changes

2022-07-21 19:45 UTC, Rebecca-Stone reviewed
The package-lock.json needs to be edited to merge, but everything else looks great! The code look clean and dry, great job!

2022-07-28 19:17 UTC, laurensruiz approved these changes
The endpoints made look good and more accessible. Updates to the model also look great and easier to understand for future devs. The code looks clean.

2022-07-29 00:26 UTC, closed without merging