BL-365 [BACK END] patch/instructor_newsfeed/sort_posts_newest_to_oldest
BloomTech-Labs/coder-heroes-be pull request #115
Opened 2022-08-11 04:30 UTC by anastasia-lapteva

## Description

Jira Ticket # **BL-365** Patch: InstructorNewsFeed currently list posts from oldest to newest.

Co-Author: **Vasilii Garanin**

## Fixes

InstructorNewsFeed now displays the most recent posts at the top of the web browser.

## Loom Video

https://www.loom.com/share/78515bca4dd14a8b9e9b60080e0d1d92

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have removed unnecessary comments/console logs from my code
- [X] I have made corresponding changes to the documentation if necessary (optional)
- [X] My changes generate no new warnings
- [X] I have checked my code and corrected any misspellings
- [X] No duplicate code left within changed files
- [X] Size of pull request kept to a minimum
- [X] Pull request description clearly describes changes made & motivations for said changes

2022-08-11 15:29 UTC, Rlauckern approved these changes, later dismissed
Great job with the backend. The finished sort posts tickets on both sides are nicely done and your loom video demonstrated your knowledge of your actions.

2022-08-11 16:00 UTC, Roadlyfe approved these changes
I'm a little confused by the check failures on data migrations so I'm going to look that up. Great work!

2022-08-11 19:00 UTC, reneetro submitted a review, later dismissed
I'm not quite familiar with the "check failures" on the migrations, I will have to do some research. Everything else looked clean!

2022-08-11 19:30 UTC, anastasia-lapteva commented
Thanks for the feedback, everyone. It looks like checks are failing because eslint is not happy with my spacing, and `npm run format` is not working. I messaged with Ash Tilawat and he is looking into this.

2022-08-12 15:20 UTC, Roadlyfe submitted a review, later dismissed
nice work!

2022-08-12 16:17 UTC, AnthonyLayne approved these changes, later dismissed
Investigated the check failures a bit, it looks like it may not like the double quotes on line 22 for the description in the seed file. From what I could find it looks like you can't use double quotes in the database. Could be wrong though. If you click on the note icon with the checkmark on the top right of the check failure, you can see more of the error.

2022-08-12 16:30 UTC, anastasia-lapteva commented
@AnthonyLayne thanks for your help! I initially went with double quotes to avoid using the \ backslash in the description text. But based on your comment I swapped back to single quotes and added the backslash before apostrophes. I also added in eslint-disable for good measure and now checks are passing :-)

2022-08-12 16:58 UTC, AnthonyLayne approved these changes, later dismissed
Your code looks good. Thank you for fixing the errors and fixing render order of the newsfeed once an article has been edited. Great Job!

2022-08-12 16:59 UTC, Cassius-Cassity approved these changes, later dismissed
Pardon my ignorance but why did so many files on package-lock.json have so many deletions?

2022-08-12 22:14 UTC, Irving-Delgad0 approved these changes, later dismissed
Yeah im gonna second the package.json question. seems like there are a lot of changes. seems unusual but i could be wrong

2022-08-12 22:15 UTC, dshipuk requested changes, later dismissed
As somebody mentioned the package-lock.json has a lot of deletions seems like an accident occurred somebody should review this before merging

2022-08-13 03:13 UTC, techlando approved these changes, later dismissed
Not sure why so much deleted code
But the written code is good. Great job adding data tables and schema

2022-08-13 03:55 UTC, Rlauckern approved these changes, later dismissed
Good tables and schema! Looks like a lot needed to change and written well.

2022-08-15 15:16 UTC, gclancy121 approved these changes, later dismissed
looks good to me

2022-08-15 15:36 UTC, Roadlyfe approved these changes, later dismissed
Looks great! No obvious bugs that  I can see.

2022-08-15 17:15 UTC, merged

2022-08-19 16:49 UTC, ryan-hamblin reviewed
Straightforward work. Please don't disable our linter. It's there to project everyone. Instead be sure your code formats to the proper style outlined in your `lint/prettier rc` files

2022-08-19 16:49 UTC, ryan-hamblin commented on data/migrations/20211103214447_newsfeed.js
> +exports.up = (knex) => {/* eslint-disable */
Let's not disable disable our linter.

2022-08-19 16:49 UTC, ryan-hamblin commented on data/migrations/20211103214447_newsfeed.js
> +exports.up = (knex) => {/* eslint-disable */
Please run the `npm lint-fix` command to format your documents properly in lieu of disabling the linter.

2022-08-19 16:49 UTC, ryan-hamblin commented on data/seeds/013_newsfeed.js
> +exports.seed = function (knex) {/* eslint-disable */
please don't disable the linter.