Payment w/ Stripe; router
BloomTech-Labs/coder-heroes-be pull request #28
Opened 2021-12-20 04:58 UTC by zach-morris-txt

This is a WIP for BE viewing. 
Will implement and submit LOOM video after meeting with BE team.

2021-12-22 00:53 UTC, AshleyCoder3 commented
Have questions about installations. will find out tomorrow

2022-01-20 16:27 UTC, DanielReinagel requested changes
Based on the code, you'd have to go to the route "/payment/payment" which seems somewhat redundant. Change that and this probably looks good.

2022-01-21 16:25 UTC, jonahjtr approved these changes
I love the consolidating and pretifying of the code

2022-01-21 17:46 UTC, Ryan-E-Mark approved these changes
Seconding what Daniel mentioned about the route being /payment/payment, not a big issue but could be a little cleaner. Other than that it looks like a great implementation of Stripe, good job getting this set up!

2022-02-15 17:26 UTC, 19jlevitre approved these changes
Looks good to me, possibly need to change how the error gets handled on line 36 of the striperouter file, but if logging it to the console is all we really need then looks great.

2022-02-17 17:57 UTC, mcmillanj commented on api/payment/stripeRouter.js
> +
router.post('/payment', (req,res) => {
const body ={ 
source: req.body.token.id,
amount: req.body.amount, //call amount when we generate request on front end
currency: 'USD'
}
})

2022-02-17 18:33 UTC, mcmillanj commented on api/payment/stripeRouter.js
> +const stripe = require('stripe')(process.env.STRIPE_KEY);
//in server.js 
if( process.env.Node_ENV  !==  'production') require('dotenv').config();
conSt stripe = require('stripe')(process.env.STRIPE_SECRET_KEY);

2022-02-17 19:25 UTC, mcmillanj requested changes
made some suggestion towards this ,I am talking to paul about handling this

2022-02-21 05:07 UTC, merged