fixed typos throughout endpoints and readme
BloomTech-Labs/coder-heroes-be pull request #40
Opened 2022-01-21 19:17 UTC by CamMeiners

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have removed unnecessary comments/console logs from my code
- [ ] I have made corresponding changes to the documentation if necessary (optional)
- [ ] My changes generate no new warnings
- [ ] I have checked my code and corrected any misspellings
- [ ] No duplicate code left within changed files
- [ ] Size of pull request kept to a minimum
- [ ] Pull request description clearly describes changes made & motivations for said changes

2022-01-25 20:03 UTC, nforman91 approved these changes
Thanks for fixing the typos! Remember to add links to the Trello card & Loom video

2022-01-28 02:05 UTC, RoseGabriely requested changes
Lookin good so far! Keep going :)

2022-01-28 02:05 UTC, RoseGabriely commented on api/app.js
> +app.use(['/course-type', '/course-types', '/course'], courseTypesRouter);
Could you also add /courses?

2022-01-28 02:05 UTC, RoseGabriely commented on README.md
> +| [DELETE]| /class-instance/:class-id | Returns the class object with the specified `id`. Deletes specific class.
Thanks for adding this! Could we style this a bit better so that the table columns align?

2022-02-02 16:50 UTC, CamMeiners commented on README.md
> +| [DELETE]| /class-instance/:class-id | Returns the class object with the specified `id`. Deletes specific class.
Done

2022-02-02 16:50 UTC, CamMeiners commented on api/app.js
> +app.use(['/course-type', '/course-types', '/course'], courseTypesRouter);
done

2022-02-03 21:17 UTC, RoseGabriely approved these changes

2022-02-14 22:40 UTC, katherineyevsukov approved these changes
Great job catching all the necessary syntax and formatting changes. Routes are much more logical and clear now. Looks like a lot of work was done and it all looks great.

2022-02-14 22:40 UTC, katherineyevsukov commented on README.md
Readme formatting updates looks good

2022-02-14 22:40 UTC, katherineyevsukov commented on __tests__/routes/newsfeed.test.js
>    });
Updates make sense. Status codes are now correct

2022-02-14 22:40 UTC, mcmillanj approved these changes
approved, mostly syntacs changes and a few route fillens. but all look great

2022-02-14 22:40 UTC, mcmillanj commented on README.md
>  <br />
Read had minor changes that were consistent with database and formatting

2022-02-16 04:15 UTC, merged