added max and min age on class middleware
BloomTech-Labs/coder-heroes-be pull request #51
Opened 2022-02-03 19:58 UTC by LeonelHays

## Description

Trello card: https://trello.com/c/hK3T89yR/167-update-classes-table-to-include-new-inputs

I added the max and min inputs for the class middleware because the stakeholder gave us an idea of how it is going to work. Both input fields are integers and are null-able since it is just a recommendation.
(We may need to update the seeds in the future.)

## Loom Video

https://www.loom.com/share/b51640d20f4a4f96966ef121c971f3a4

- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have removed unnecessary comments/console logs from my code
- [ ] My changes generate no new warnings
- [ ] I have checked my code and corrected any misspellings
- [ ] No duplicate code left within changed files
- [ ] Size of pull request kept to a minimum
- [ ] Pull request description clearly describes changes made & motivations for said changes

2022-02-03 20:34 UTC, CamMeiners approved these changes
The code looks good. Thinking about edge case scenarios, can we make it so the max_age integer cannot be less than the min_age?

2022-02-03 21:55 UTC, RoseGabriely requested changes
Great start, we also need to go back and make sure that anything that depended on the previous code has been updated. This will include all of the seeds, models, and middleware that were using this table.

2022-02-03 21:55 UTC, RoseGabriely commented on README.md
> +
Thanks for adding this to the documentation!

2022-02-03 21:55 UTC, RoseGabriely commented on data/migrations/20211102125418_courses.js
>        table.integer('open_seats_remaining');
could you please add a day field (days of the week), and a course_type_id that references the course_types table

2022-02-15 17:39 UTC, 19jlevitre reviewed
Changes look good and code looks clean. Very thoughtful to add such good docs to the ReadMe. Seems like Rose is right about adding the days available for classes, but that seems like itd be it

2022-02-21 20:43 UTC, mcmillanj approved these changes
you fix the changes that were reguested plus the min and max  age  added to table .great job

2022-03-03 08:01 UTC, closed without merging