Created courses endpoints
BloomTech-Labs/coder-heroes-be pull request #6
Opened 2021-11-08 17:30 UTC by WillisLi

What we did: Implemented course routes and model to table and updated course migrations and seeds.
Files we added:  courseModel.js, courseRouter.js
Why were the changes made: To push up some endpoints for frontend.

Co-authored-by: Andrew Cummings <andrew.amalee@gmail.com>
[Loom Video](https://www.loom.com/share/8caa4f8ac67e42cf9ddf110e22d11f4a)

2021-11-08 17:37 UTC, CptHappyHands commented on data/migrations/20211102124951_inboxes.js
> +      2;
Remove the 2. Pretty sure it was just a typo

2021-11-08 18:56 UTC, MikeLikesCode approved these changes

2021-11-08 18:56 UTC, MikeLikesCode commented on api/course/courseModel.js
> +
Nice names for the DB functions. This will definitely help the other teams in the future.

2021-11-08 18:59 UTC, JoeyMBrown requested changes
Looks like the package-lock.json got uploaded on here, was this on purpose?  Other than that everything looks good.  Loads of changes here awesome job back-end! @WillisLi

2021-11-08 19:04 UTC, fernando817mm requested changes
Hey guys, it might be a good idea to drop the tables in reverse order of how they were created.

2021-11-08 20:02 UTC, WillisLi commented
> Looks like the package-lock.json got uploaded on here, was this on purpose? Other than that everything looks good. Loads of changes here awesome job back-end! @WillisLi

Yep! That was on purpose, Ryan let us know that some stuff would be outdated, so we made the changes accordingly, and package-lock.json is part of that necessary change.

2021-11-08 20:12 UTC, WillisLi commented
> Hey guys, it might be a good idea to drop the tables in reverse order of how they were created. Looking good though!

Sorry, which tables are you referring to? We checked the drop migrations and don't see any in particular that need to be fixed.

2021-11-08 21:34 UTC, CptHappyHands reviewed
Looks good to me!

2021-11-08 21:42 UTC, JoeyMBrown approved these changes
Awesome!  Thanks for the quick response!

2021-11-09 15:06 UTC, bradlylewis commented on .github/workflows/ci.yml
> -      - name: Run Tests
What are these 7 lines of code that were removed?

2021-11-09 15:08 UTC, bradlylewis approved these changes

2021-11-09 15:50 UTC, fernando817mm commented
> > Hey guys, it might be a good idea to drop the tables in reverse order of how they were created. Looking good though!
> 
> Sorry, which tables are you referring to? We checked the drop migrations and don't see any in particular that need to be fixed.

exports.down in each migration file. I may be wrong but I thought that dropping the tables in reverse order from how they were created was best practice. Just asked Ash though and as long as you're consistent with the order of your tables it should be fine!

2021-11-09 15:51 UTC, fernando817mm approved these changes
Looks good!

2021-11-09 16:02 UTC, WillisLi commented on .github/workflows/ci.yml
> -      - name: Run Tests
Just removed the SonarScan tests. Ryan approved these changes when reviewing what old setup code needed to be changed.

2021-11-09 16:51 UTC, merged