Feature/get instructor id middleware
BloomTech-Labs/coder-heroes-be pull request #84
Opened 2022-04-05 19:35 UTC by aaronpear

## Description

This PR adds a new middleware function that allows endpoints to easily extract the instructor_id of the currently active user via pre-existing profile data provided with each user request. This will enable a simpler workflow when building new endpoints or frontend components that want instructors to only handle data specific to their instructor profile.

Fixes # (issue)

## Loom Video

https://www.loom.com/share/79b78818b981406aa9ce9af63fd26b44

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [ ] I have made corresponding changes to the documentation if necessary (optional)
-  [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

2022-04-05 23:48 UTC, sagun1151 approved these changes

2022-04-05 23:48 UTC, sagun1151 commented on api/instructor/instructorMiddleware.js
>  };
Nicely implemented middleware and model. looks good to go but just asking where it would be implemented in the instruct routers

2022-04-06 15:44 UTC, jmerz826 requested changes
Great work. Only minor change would be changing instructor_id to instructor for readability

2022-04-06 15:44 UTC, jmerz826 commented on api/instructor/instructorMiddleware.js
> +// ../middleware/authRequired.js must be called before calling this middleware
good comment, helps teammates' comprehension

2022-04-06 15:44 UTC, jmerz826 commented on api/instructor/instructorMiddleware.js
> +  const instructor_id = await Instructors.findInstructorIdByProfileId(
```suggestion
  const instructor = await Instructors.findInstructorIdByProfileId(
```

2022-04-06 15:44 UTC, jmerz826 commented on api/instructor/instructorMiddleware.js
> +  if (instructor_id) {
```suggestion
  if (instructor) {
```

2022-04-06 15:44 UTC, jmerz826 commented on api/instructor/instructorMiddleware.js
> +    req.instructor_id = instructor_id.instructor_id;
```suggestion
    req.instructor_id = instructor.instructor_id;
```

2022-04-06 20:55 UTC, jmerz826 approved these changes

2022-04-07 00:58 UTC, merged

2022-04-07 01:39 UTC, MaryAngelique approved these changes
The quality of code is impeccable. Well done!