Started working on post
BloomTech-Labs/coder-heroes-be pull request #89
Opened 2022-04-18 18:34 UTC by EduarddoEscobar

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Loom Video

Please paste a link here of a quick loom video walking through what you did in your PR .

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have removed unnecessary comments/console logs from my code
- [ ] I have made corresponding changes to the documentation if necessary (optional)
- [ ] My changes generate no new warnings
- [ ] I have checked my code and corrected any misspellings
- [ ] No duplicate code left within changed files
- [ ] Size of pull request kept to a minimum
- [ ] Pull request description clearly describes changes made & motivations for said changes

2022-04-22 16:36 UTC, joeys1122 approved these changes
Great job getting these endpoints up Eduardo and Lizzy, your code is very clean and adds a ton of functionality!

2022-04-25 15:24 UTC, dconley1212 approved these changes
This looks great! Refactored the code base to look a lot better and you have the endpoints all working!

2022-04-26 10:13 UTC, peterdavidconley approved these changes
Middleware, Model.js, and README descriptions all look solid. Great job at cleaning up the console logs and other unnecessary code. Great use of the async/await for the ChildRouter post endpoint.

2022-04-29 23:41 UTC, paulstgermain requested changes
This is overall solid work - consistently structured, clean, and without introducing bugs! Just one change to make in our error handling and this would be good to merge up!

2022-04-29 23:41 UTC, paulstgermain commented on api/children/childrenMiddleware.js
> +    next({ status: 403, message: 'This is not your child please stay away!' });
We _might_ want to adjust this error message to be slightly less accidentally hostile - keep in mind, we want to hand useful error messages up to the FE that don't necessarily accuse our users!

2022-05-02 23:00 UTC, paulstgermain approved these changes

2022-05-02 23:01 UTC, merged