refactored courses by id endpoint
BloomTech-Labs/coder-heroes-be pull request #98
Opened 2022-04-26 21:42 UTC by luisbryandr

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Loom Video

(https://www.loom.com/share/b38d602e0d324e1cb7ffacb053a6f708)

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have removed unnecessary comments/console logs from my code
- [X] I have made corresponding changes to the documentation if necessary (optional)
- [ X] My changes generate no new warnings
- [ X] I have checked my code and corrected any misspellings
- [ X] No duplicate code left within changed files
- [ X] Size of pull request kept to a minimum
- [ X] Pull request description clearly describes changes made & motivations for said changes

2022-05-03 15:49 UTC, ShanaeL29 approved these changes
Nice catch recognizing a piece of repetitive code and removing it to reduce database calls. Even a simple change can make a big enough difference in the final product. Continue to pay good attention to detail and review your team's work as this is a great skill to have in this industry.

2022-05-04 22:21 UTC, cavazosgeorge requested changes
Hey @luisbryandr great job noticing the redundant API calls within this endpoint. I wrote this endpoint initially and learned something from your loom explanation. 

Don't forget to write a description explaining the overview of this change and why it was needed!

2022-05-04 22:36 UTC, JorgeEvangelista500 approved these changes
Great job changing the documentation, maybe adding a catch to stay consistent with other endpoints

2022-05-04 23:26 UTC, JessWillCode approved these changes
Nice Refactor! I think that the ReadME is easier to read, and the function in the code is so much cleaner to read and understand. Thanks for this!

2022-05-04 23:26 UTC, JessWillCode commented on README.md
> +| [PUT]    | /profile/                                                                                                              | Returns an event object with the specified `okta`. Updates specif
These look almost identical, so confused why it's showing that it was removed and then added back.

2022-05-04 23:26 UTC, JessWillCode commented on api/courses/coursesRouter.js
> +  res.status(200).json(req.course);
Nice job refactoring the code down! This is so much cleaner than having the model function inside.

2022-05-05 15:21 UTC, EduarddoEscobar approved these changes
Great work making the code more DRY!

2022-05-06 01:16 UTC, Ike888 approved these changes
Clean code! And great work refactoring.

2022-06-15 03:04 UTC, merged