Created GET/instructor/profile/profile_id route
BloomTech-Labs/coder-heroes-be pull request #99
Opened 2022-04-28 18:15 UTC by cavazosgeorge

## Description

We built out the instructor/profile/:profile_id endpoint that allows us to request instructors based on their specifc profile_ids. 

Collaborators: [Berenika Ahmetaj](https://github.com/berenika14), [Anthony Amaya](https://github.com/aamay022)

Fixes # (issue)

We created a new model function `findInstructorProfileByProfileId` that sends us back the entire instructor profile object. 

## Loom Video

Please paste a link here of a quick loom video walking through what you did in your PR .

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

2022-04-29 14:35 UTC, JorgeEvangelista500 approved these changes
Great work! everything works as intended, a great addition moving forward, to be able to get a specific instructor.

2022-04-30 15:15 UTC, peterdavidconley approved these changes
Great job on clean and simple code for "findInstructorProfileByProfileId". .Then & .Catch statements look flawless. No further critiques from me.

2022-05-02 23:05 UTC, paulstgermain requested changes
This PR needs a Loom recording walking us through your work before I can officially review it! 😱 

Please record a short Loom walking us through the work you did here and add a link to it in your description as soon as you can.

2022-05-03 15:19 UTC, EduarddoEscobar approved these changes
Overall good work just some slight changes to stay more consistent

2022-05-03 15:19 UTC, EduarddoEscobar commented on api/instructor/instructorRouter.js
> +    .catch(errorhandler);
you can change the .catch(errorhandler) to .catch(next) to stay more consistent with the other endpoint.

2022-05-03 15:19 UTC, EduarddoEscobar commented on README.md
> +| [GET]  | /instructor/profile/profile_id | Returns a profile object of a specific instructor .                                                   |
Changing /instructor/profile/profile_id to /instructor/profile/:profile_id could help more quickly understand that you need to pass the profile_id for the endpoint

2022-05-03 21:49 UTC, Berenika14 commented on api/instructor/instructorRouter.js
> +    .catch(errorhandler);
Hey thanks for catching that recommendation, I just changed it, and looks much more consistent and cleaner with the rest of the code.

2022-05-03 22:16 UTC, Berenika14 commented
> This PR needs a Loom recording walking us through your work before I can officially review it! 😱
> 
> Please record a short Loom walking us through the work you did here and add a link to it in your description as soon as you can.


Hey, @paulstgermain Loom video added. 🙂

2022-05-06 01:11 UTC, Ike888 approved these changes
Great work done here! and some ideas for the Auth0 as well.

2022-06-21 16:01 UTC, kylerostler approved these changes
Great job with this, love how useful you made the endpoint for getting the entire instructor profile object.

2022-06-27 20:00 UTC, jose-mercado approved these changes
Nice job creating an endpoint to fetch an instructor based on a profile ID! Looks like there are some conflicts in the README and api/instructor/instructorRouter.js, but aside from that, this looks great!

2022-06-28 14:40 UTC, dirkknibbe approved these changes

2022-06-28 14:40 UTC, dirkknibbe commented on api/instructor/instructorRouter.js
> +router.get('/profile/:profile_id', authRequired, (req, res, next) => {
Good job using the same format for functions that come before, very readable.

2022-07-16 13:03 UTC, attaris978 approved these changes
Your code is minimalistic, efficient, and easy to read. Very well done.
More emphatically, I absolutely adore your attention to display detail with the README.md file. You took something that was annoying to follow and made it visually appealing and eminently more readable.
The only improvement I can think of is to be careful of punctuation parallel structure -- some of your Description column entries use periods, others do not -- though this is hardly a substantive issue.

2022-07-29 00:26 UTC, closed without merging